### ISSUE TITLE
Debian Bullseye missing ansible-core package

### ISSUE THREAD

**Issue by AlexDaichendt** [Thulium-Drake/ansible-role-ansible_semaphore#1]
Debian Bullseye apparently does not yet package `ansible-core`. Therefore, the role fails to install. 

For reference: 
https://packages.debian.org/search?keywords=ansible-core&searchon=names&suite=bullseye&section=all

**Comment by Thulium-Drake** [comment]
Ah, right, I haven't used the Debian-packaged Ansible version in years (as it used to lag way too far behind). I'm so used to that, I didn't include it in this role :-)

I've updated the role with a fix in 0.0.3 :)

**Comment by AlexDaichendt** [comment]
Thank you so much !! 

These are the pains of using Debian every day -.-
