### ISSUE TITLE
Recent releases missing in Ansible Galaxy

### ISSUE THREAD

**Issue by stdevel** [Thulium-Drake/ansible-role-ansible_semaphore#3]
Hi,
thanks for your semaphore role!

I just saw, that [Ansible Galaxy](https://galaxy.ansible.com/thulium_drake/ansible_semaphore) only lists version *0.0.2* of your role, while the Git repository also offers *0.0.3* and *0.0.4*. I assume that you need to re-import them into Galaxy.

**Comment by Thulium-Drake** [comment]
Hi there!

Thanks for the note! Yes, I know... That's some of the better rug-pulling in Molecule, they removed 'molecule lint' without deprecating it first which broke _all_ of my CI/CD... Working on it :-)

For now I have imported them manually!

**Comment by stdevel** [comment]
Awesome, thanks for the fast reply! :)
