### ISSUE TITLE
why ansible-core is needed? 

### ISSUE THREAD

**Issue by lkthomas** [Thulium-Drake/ansible-role-ansible_semaphore#4]
TASK [thulium_drake.ansible_semaphore : Ensure dependencies] ************************************************
fatal: [host-1.net]: FAILED! => {"changed": false, "msg": "No package matching 'ansible-core' is available"}

I am running Ubuntu 20.04, why would the role need ansible-core on the host itself? 

from "roles/thulium_drake.ansible_semaphore/tasks/main.yml" file, 

` - name: 'Ensure dependencies'`
`    ansible.builtin.package:`
`     name:`
`        - 'git'`
`        - "{{ semaphore_ansible_package }}"`

I don't see why the ansible-core is needed for the hosts as dependency requirement.

**Comment by lkthomas** [comment]
I just tested by removing semaphore_ansible_package line, nothing wrong

**Comment by Thulium-Drake** [comment]
Well, if you don't install Ansible, Semaphore can't run anything with it :) 

https://docs.ansible-semaphore.com/administration-guide/installation_manually

This guide mentions to install ansible with Pip, but that's not always required if your distro comes with a package

**Comment by lkthomas** [comment]
> Well, if you don't install Ansible, Semaphore can't run anything with it :)
> 
> https://docs.ansible-semaphore.com/administration-guide/installation_manually
> 
> This guide mentions to install ansible with Pip, but that's not always required if your distro comes with a package


Oh right, you are correct! I end up using another playbook to handle the installation. Thanks.
