### ISSUE TITLE
become: false when changing ownership.

### ISSUE THREAD

**Issue by bbaassssiiee** [Thulium-Drake/ansible-role-ansible_semaphore#7]
```
msg: 'chown failed: [Errno 1] Operation not permitted: b''/tmp/semaphore.rpm'''
```
https://github.com/Thulium-Drake/ansible-role-ansible_semaphore/blob/7fa30dbdfac8f28c1b65a872d5343bd1b06a05d6/tasks/main.yml

    - name: 'Ensure Semaphore package file'  # yamllint disable rule:line-length
      ansible.builtin.get_url:
        url: "https://github.com/semaphoreui/semaphore/releases/download/v{{ semaphore_version }}/semaphore_{{ semaphore_version }}_linux_{{ semaphore_pkg_arch }}.{{ semaphore_pkg_extension }}"
        dest: "/tmp/semaphore.{{ semaphore_pkg_extension }}"
        owner: 'root'
        group: 'root'
        mode: '0644'
      become: false

**Comment by bbaassssiiee** [comment]
Running the role twice masks the issue. Better not chown to root when become is false. (You're not running playbooks as root are you?)

**Comment by Thulium-Drake** [comment]
Nope, I run my playbooks with a user that has ```sudo``` privileges :-)

Thanks for the fix! There was no particular reason for root to own these files, though it's habit for me to always add an owner to files :-)

**Comment by bbaassssiiee** [comment]
Thanks for the quick merge.
